module.exports = [
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-solus-round-toilet-suite-close-coupled-9502264",
        "Product Name": "Posh Solus Round Toilet Suite Close Coupled S-Trap with Quick Release Soft Close Seat White / Chrome (4 Star)",
        "Product Code": "9502264",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/b480a244d64234bb/original/Specification-Sheet-Posh-Solus-Toilet-Suite-Close-Coupled-with-Quick-Release-Soft-Close-Seat-White-Chrome-4-Star.pdf",
        "P Trap Setout": null,
        "S Trap Setout": "145",
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-solus-square-close-coupled-back-to-wall-9507919",
        "Product Name": "Posh Solus Square Close Coupled Back to Wall Bottom Inlet Toilet Suite S&P Trap Soft Close Quick Release Seat White/ Chrome (4 Star)",
        "Product Code": "9507919",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/3ef00f4554dfdb06/original/Specification-Sheet-Posh-Solus-Close-Coupled-Back-to-Wall-Back-Inlet-Toilet-Suite-S-P-Trap-with-Soft-Close-Quick-Release-Seat-White-Chrome-4-Star.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": "95",
        "S Trap Max Setout": "185",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/base-link-toilet-suite-s-trap-with-seat-white-4-9503292",
        "Product Name": "BASE Link Toilet Suite S Trap with Seat White (4 Star)",
        "Product Code": "9503292",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/f1e0a837204a799a/original/Specification-Sheet-BASE-Link-Toilet-Suite-S-Trap-with-Seat-White-4-Star.pdf",
        "P Trap Setout": "185",
        "S Trap Setout": null,
        "S trap Min Setout": "150",
        "S Trap Max Setout": "250",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-solus-round-close-coupled-s-trap-toilet-9500993",
        "Product Name": "Posh Solus Round Close Coupled S Trap Toilet Suite With Standard Seat White / Chrome (4 Star)",
        "Product Code": "9500993",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/b480a244d64234bb/original/Specification-Sheet-Posh-Solus-Toilet-Suite-Close-Coupled-with-Quick-Release-Soft-Close-Seat-White-Chrome-4-Star.pdf",
        "P Trap Setout": null,
        "S Trap Setout": "145",
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/caroma-cameo-close-coupled-s-trap-bottom-1810440",
        "Product Name": "Caroma Cameo Close Coupled S Trap Bottom Inlet Toilet Suite Soft Close Seat White (4 Star)",
        "Product Code": "1810440",
        "Spec Sheet": "https://d12qbzr1dyleru.cloudfront.net/m/b5448d02e94c3512/Web_1200x900-Cameo-Close-Coupled-Toilet-Suite-S-Trap-Soft-Close-Seat-Bottom-Inlet-White-4-Star-.jpg",
        "P Trap Setout": null,
        "S Trap Setout": null,
        "S trap Min Setout": "90",
        "S Trap Max Setout": "190",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/kado-lux-close-coupled-back-to-wall-rimless-1805495",
        "Product Name": "Kado Lux Close Coupled Back To Wall Rimless Overheight Bottom Inlet Toilet Suite with Thin Soft Close Quick Release Seat (4 Star)",
        "Product Code": "1805495",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/8ac338e80de87e1c/original/Specification-Sheet-Kado-Lux-Close-Coupled-Back-To-Wall-Rimless-Overheight-Bottom-Inlet-Toilet-Suite-with-Thin-Soft-Close-Quick-Release-Seat-4-Star.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": "95",
        "S Trap Max Setout": "190",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/american-standard-cygnet-square-hygiene-rim-close-9509830",
        "Product Name": "American Standard Cygnet Square Hygiene Rim Close Coupled Back to Wall Bottom Inlet Toilet Suite with American Standard SpaLet E-Bidet Seat White (4 Star)",
        "Product Code": "9509830",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/5906bd7b357219fd/original/Specification-Sheet-American-Standard-Spalet-Short-E-Bidet-Seat-White.pdf",
        "P Trap Setout": null,
        "S Trap Setout": null,
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/american-standard-cygnet-round-1810109",
        "Product Name": "American Standard Cygnet Round Overheight Hygiene Rimless Close Coupled Back To Wall Bottom Inlet Toilet Suite White (4 Star)",
        "Product Code": "1810109",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/3af721f9d7821630/original/American-Standard-Cygnet-Round-Overheight-Hygiene-Rimless-Close-Coupled-Back-To-Wall-Bottom-Inlet-Toilet-Suite-White-4-Star.pdf",
        "P Trap Setout": "190",
        "S Trap Setout": null,
        "S trap Min Setout": "140",
        "S Trap Max Setout": "260",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/american-standard-cygnet-square-1810108",
        "Product Name": "American Standard Cygnet Square Overheight Hygiene Rimless Close Coupled Back To Wall Bottom Inlet Toilet Suite White (4 Star)",
        "Product Code": "1810108",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/593ffea9bb6ae075/original/American-Standard-Cygnet-Square-Overheight-Hygiene-Rimless-Close-Coupled-Back-To-Wall-Bottom-Inlet-Toilet-Suite-White-4-Star.pdf",
        "P Trap Setout": "190",
        "S Trap Setout": null,
        "S trap Min Setout": "140",
        "S Trap Max Setout": "260",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/roca-in-wash-inspira-rimless-close-coupled-1804803",
        "Product Name": "Roca In-Wash Inspira Rimless Close Coupled Back To Wall Toilet Suite with Soft Close Seat White (4 Star)",
        "Product Code": "1804803",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/1965e91753eaa6e3/original/Specification-Sheet-Roca-In-Wash-Inspira-Rimless-Close-Coupled-Back-To-Wall-Toilet-Suite.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": "125",
        "S Trap Max Setout": "225",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-solus-square-close-coupled-toilet-suite-p-9509510",
        "Product Name": "Posh Solus Square Close Coupled Toilet Suite P Trap with Soft Close Quick Release Seat White / Chrome New (4 Star)",
        "Product Code": "9509510",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/b480a244d64234bb/original/Specification-Sheet-Posh-Solus-Toilet-Suite-Close-Coupled-with-Quick-Release-Soft-Close-Seat-White-Chrome-4-Star.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/american-standard-studio-square-close-coupled-9506442",
        "Product Name": "American Standard Studio Square Close Coupled Toilet Suite (S Trap) with Soft Close Quick Release White (4 Star)",
        "Product Code": "9506442",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/aff2241afc5546d9/original/Specification-Sheet-American-Standard-Studio-Square-Close-Coupled-S-Trap-with-Soft-Close-Quick-Release-White-4-Star.pdf",
        "P Trap Setout": null,
        "S Trap Setout": "140",
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-solus-round-toilet-suite-closed-coupled-9502265",
        "Product Name": "Posh Solus Round Toilet Suite Closed Coupled P-Trap with Quick Release Soft Close Seat White / Chrome (4 Star)",
        "Product Code": "9502265",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/b480a244d64234bb/original/Specification-Sheet-Posh-Solus-Toilet-Suite-Close-Coupled-with-Quick-Release-Soft-Close-Seat-White-Chrome-4-Star.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/american-standard-heron-hygiene-rim-bottom-9508893",
        "Product Name": "American Standard Heron Hygiene Rim Bottom Inlet Close Coupled Back to Wall Toilet Suite with Soft Close Quick Release Seat White (4 Star)",
        "Product Code": "9508893",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/31342b8a27c0aa47/original/Specification-Sheet-American-Standard-Heron-Square-Hygiene-Rim-Bottom-Inlet-Close-Coupled-Back-to-Wall-Toilet-Suite-with-Soft-Close-Quick-Release-Seat-White-4-Star-.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": "90",
        "S Trap Max Setout": "140",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/kado-lux-close-coupled-back-to-wall-rimless-1805493",
        "Product Name": "Kado Lux Close Coupled Back To Wall Rimless Overheight Bottom Inlet Toilet Suite with Soft Close Quick Release Seat (4 Star)",
        "Product Code": "1805493",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/02e666f0ec048288/original/Specification-Sheet-Kado-Lux-Close-Coupled-Back-To-Wall-Rimless-Overheight-Bottom-Inlet-Toilet-Suite-with-Soft-Close-Quick-Release-Seat-4-Star.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": "95",
        "S Trap Max Setout": "190",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-domaine-close-coupled-rimless-toilet-9508004",
        "Product Name": "Posh Domaine Close Coupled Rimless Toilet Suite S Trap with Soft Close Quick Release Seat White Chrome (4 Star)",
        "Product Code": "9508004",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/55b608535548daaa/original/Component-Listing-Posh-Domaine-Soft-Close-Quick-Release-Toilet-Seat-White.pdf",
        "P Trap Setout": null,
        "S Trap Setout": "145",
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-canterbury-low-level-toilet-suite-with-9509238",
        "Product Name": "Posh Canterbury Low Level Toilet Suite with Quick Soft Close Seat S Trap White (4 Star)",
        "Product Code": "9509238",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/19ff36c2adebf22c/original/Specification-Sheet-Posh-Canterbury-Low-Level-Toilet-Suite-White-4-Star-.pdf",
        "P Trap Setout": null,
        "S Trap Setout": null,
        "S trap Min Setout": "190",
        "S Trap Max Setout": "240",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/roca-debba-close-coupled-toilet-suite-p-trap-9508934",
        "Product Name": "Roca Debba Close Coupled Toilet Suite P Trap Bottom Inlet with MK2 Soft Close Quick Release Toilet Seat White Chrome (4 Star)",
        "Product Code": "9508934",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/78d0c9e203fa3f45/original/Component-Listing-Debba-Close-Coupled-Toilet-Suite-P-Trap-Bottom-Inlet-With-Soft-Close-MK2-Seat-White-Chrome-4-Star.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/axa-wild-close-coupled-back-to-wall-rimless-9509201",
        "Product Name": "AXA Wild Close Coupled Back To Wall Rimless Toilet Suite Soft Close Quick Release Seat White (4 Star)",
        "Product Code": "9509201",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/735f614723459c65/original/Specification-Sheet-Axa-Wild-Close-Coupled-Back-To-Wall-Rimless-Toilet-Suite-Soft-Close-Quick-Release-Seat-White-4-Star-.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": "135",
        "S Trap Max Setout": "235",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/american-standard-studio-square-close-coupled-9506441",
        "Product Name": "American Standard Studio Square Close Coupled Toilet Suite (P Trap) with Soft Close Quick Release White (4 Star)",
        "Product Code": "9506441",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/d319c3ff108228af/original/Specification-Sheet-American-Standard-Studio-Square-Close-Coupled-P-Trap-with-Soft-Close-Quick-Release-White-4-Star.pdf",
        "P Trap Setout": "185",
        "S Trap Setout": null,
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/laufen-palace-close-coupled-back-to-wall-9506227",
        "Product Name": "LAUFEN Palace Close Coupled Back To Wall Bottom Inlet S&P Trap Toilet Suite with Soft Close Seat White (4 Star)",
        "Product Code": "9506227",
        "Spec Sheet": "https://d12qbzr1dyleru.cloudfront.net/m/cc19e6fe6f6fd1c4/original/Specification-Sheet-LAUFEN-Palace-Close-Coupled-Back-To-Wall-Bottom-Inlet-S-P-Trap-Toilet-Suite-with-Soft-Close-Seat-White-4-Star-.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": "155",
        "S Trap Max Setout": "255",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-canterbury-close-coupled-toilet-suite-9502334",
        "Product Name": "Posh Canterbury Close Coupled Toilet Suite with Oak Cherry Seat White (4 Star)",
        "Product Code": "9502334",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/66e19c60415a4e4c/original/Specification-Sheet-Posh-Canterbury-Close-Coupled-Toilet-Suite-White-4-Star-.pdf",
        "P Trap Setout": null,
        "S Trap Setout": "155",
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-canterbury-low-level-toilet-suite-with-oak-9502331",
        "Product Name": "Posh Canterbury Low Level Toilet Suite with Oak Cherry Seat White (4 Star)",
        "Product Code": "9502331",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/19ff36c2adebf22c/original/Specification-Sheet-Posh-Canterbury-Low-Level-Toilet-Suite-White-4-Star-.pdf",
        "P Trap Setout": null,
        "S Trap Setout": null,
        "S trap Min Setout": "190",
        "S Trap Max Setout": "240",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/american-standard-studio-round-close-coupled-9506439",
        "Product Name": "American Standard Studio Round Close Coupled Toilet Suite (P Trap) with Soft Close Quick Release White (4 Star)",
        "Product Code": "9506439",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/ca24002548eaf5d9/original/Specification-Sheet-American-Standard-Studio-Round-Close-Coupled-P-Trap-with-Soft-Close-Quick-Release-White-4-Star.pdf",
        "P Trap Setout": "185",
        "S Trap Setout": null,
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/american-standard-signature-hygiene-rim-close-9509682",
        "Product Name": "American Standard Signature Hygiene Rim Close Coupled Back to Wall Bottom Inlet Toilet Suite with Soft Close Quick Release White Seat (4 Star)",
        "Product Code": "9509682",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/21a7ab28b599406f/original/Specification-Sheet-American-Standard-Signature-Close-Coupled-Back-to-Wall-Bottom-Inlet-Toilet-Suite-with-Soft-Close-Quick-Release-White-Seat-4-Star-.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": "140",
        "S Trap Max Setout": "250",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/roca-debba-close-coupled-back-to-wall-bottom-9508939",
        "Product Name": "Roca Debba Close Coupled Back To Wall Bottom Inlet Toilet Suite with MK2 Soft Close Quick Release Toilet Seat White Chrome (4 Star)",
        "Product Code": "9508939",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/c20108b4666e5f0c/original/Specification-Sheet-Roca-Debba-Close-Coupled-Back-to-Wall-Bottom-Inlet-Toilet-Suite-with-Soft-Close-Quick-Release-Seat-White-4-Star.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": "95",
        "S Trap Max Setout": "155",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/american-standard-studio-round-close-coupled-9506440",
        "Product Name": "American Standard Studio Round Close Coupled Toilet Suite (S Trap) with Soft Close Quick Release White (4 Star)",
        "Product Code": "9506440",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/6c4893c0f138f828/original/Specification-Sheet-American-Standard-Studio-Round-Close-Coupled-Toilet-Suite-S-Trap-with-Soft-Close-Quick-Release-White-4-Star.pdf",
        "P Trap Setout": null,
        "S Trap Setout": "140",
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-canterbury-toilet-suite-close-coupled-9503056",
        "Product Name": "Posh Canterbury Toilet Suite Close Coupled S-Trap with Quick Release Soft Close Seat White (4 Star)",
        "Product Code": "9503056",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/66e19c60415a4e4c/original/Specification-Sheet-Posh-Canterbury-Close-Coupled-Toilet-Suite-White-4-Star-.pdf",
        "P Trap Setout": null,
        "S Trap Setout": "155",
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/american-standard-cygnet-close-coupled-back-to-9506401",
        "Product Name": "American Standard Cygnet Close Coupled Back to Wall Bottom Inlet Toilet Suite with a Soft Close Quick Release White Seat (4 Star)",
        "Product Code": "9506401",
        "Spec Sheet": "https://d12qbzr1dyleru.cloudfront.net/m/ba6cafafe1faff47/original/Technical-Guide-American-Standard-Cygnet-Close-Coupled-Back-to-Wall-Bottom-Inlet-Toilet-Suite-with-a-Soft-Close-Quick-Release-White-Seat-4-Star-.pdf",
        "P Trap Setout": "190",
        "S Trap Setout": null,
        "S trap Min Setout": "140",
        "S Trap Max Setout": "270",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-solus-square-close-coupled-toilet-suite-s-9509511",
        "Product Name": "Posh Solus Square Close Coupled Toilet Suite S Trap with Soft Close Quick Release Seat White / Chrome New (4 Star)",
        "Product Code": "9509511",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/b480a244d64234bb/original/Specification-Sheet-Posh-Solus-Toilet-Suite-Close-Coupled-with-Quick-Release-Soft-Close-Seat-White-Chrome-4-Star.pdf",
        "P Trap Setout": null,
        "S Trap Setout": "145",
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-solus-square-link-toilet-suite-s-trap-with-9505484",
        "Product Name": "Posh Solus Square Link Toilet Suite S Trap with Soft Close Seat White/ Chrome (4 Star)",
        "Product Code": "9505484",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/73101a661c33149f/original/Posh-Solus-Link-Toilet-Suite-S-Trap-with-Soft-Close-Seat-White-Chrome-4-Star.pdf",
        "P Trap Setout": null,
        "S Trap Setout": null,
        "S trap Min Setout": "170",
        "S Trap Max Setout": "280",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/caroma-forma-close-coupled-back-to-wall-bottom-9506684",
        "Product Name": "Caroma Forma Close Coupled Back To Wall Bottom Inlet Over Height Rimless Toilet Suite with Soft Close Quick Release Seat White (4 Star)",
        "Product Code": "9506684",
        "Spec Sheet": "https://d12qbzr1dyleru.cloudfront.net/m/6b08e53446cb250c/original/Technical-Guide-Caroma-Forma-Close-Coupled-Back-To-Wall-Bottom-Inlet-Over-Height-Rimless-Toilet-Suite-with-Soft-Close-Quick-Release-Seat-White-4-Star-.pdf",
        "P Trap Setout": "185",
        "S Trap Setout": null,
        "S trap Min Setout": "60",
        "S Trap Max Setout": "200",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-domaine-rimless-close-coupled-back-to-wall-9509219",
        "Product Name": "Posh Domaine Rimless Close Coupled Back to Wall Toilet Suite Bottom Inlet with Soft Close Quick Release Seat (4 Star)",
        "Product Code": "9509219",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/55b608535548daaa/original/Component-Listing-Posh-Domaine-Soft-Close-Quick-Release-Toilet-Seat-White.pdf",
        "P Trap Setout": "180",
        "S Trap Setout": null,
        "S trap Min Setout": "100",
        "S Trap Max Setout": "200",
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/base-link-toilet-suite-p-trap-with-seat-white-4-9503293",
        "Product Name": "BASE Link Toilet Suite P Trap with Seat White (4 Star)",
        "Product Code": "9503293",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/6b3a63fbd046d84f/original/Specification-Sheet-BASE-Link-Toilet-Suite-P-Trap-with-Seat-White-4-Star.pdf",
        "P Trap Setout": "185",
        "S Trap Setout": null,
        "S trap Min Setout": null,
        "S Trap Max Setout": null,
        "_type": "dict"
    },
    {
        "Page Url": "https://www.reece.com.au/product/toilets-c469/toilet-suites-c705/posh-solus-round-link-toilet-suite-s-trap-with-9502975",
        "Product Name": "Posh Solus Round Link Toilet Suite S Trap with Soft Close Seat White (4 Star)",
        "Product Code": "9502975",
        "Spec Sheet": "https://digitalassets.reecegroup.com.au/m/73101a661c33149f/original/Posh-Solus-Link-Toilet-Suite-S-Trap-with-Soft-Close-Seat-White-Chrome-4-Star.pdf",
        "P Trap Setout": null,
        "S Trap Setout": null,
        "S trap Min Setout": "170",
        "S Trap Max Setout": "280",
        "_type": "dict"
    }
]
